Document invariants of raptyMiddle
treeowl/containers pull request #2
Opened 2020-04-11 19:32 UTC by Lysxia

Also a little refactoring

- renaming `xs''FT` and `fs` to `midxs`
- renaming `s` to `lenys`
- regroup the arguments between (1) the constants, (2) those that get updated uniformly at every recursive call (representing powers of 3), and (3) the non-uniform ones
- shift the logic around `sizec` "one level up", so the new `sizec` is the old `3 * sizec` also equal to the old `sizec'`.

2020-04-11 20:40 UTC, treeowl requested changes
Definitely an improvement. One change requested before I can merge to my branch. I also have to double check that the argument regrouping doesn't muck up unboxing—GHC can get a bit fussy when there are lots of arguments.

2020-04-11 20:40 UTC, treeowl commented on containers/src/Data/Sequence/Internal.hs
> +            lastf
We should probably rename `firstf -> firstx` and `lastf -> lastx`. Could you amend that to this commit?

2020-04-13 18:09 UTC, treeowl commented
I've squashed these and added them (as a single commit) to my branch. Many thanks, @Lysxia! I have a couple questions:

1. Do you prefer to be called Li-Yao Xia or Xia Li-Yao? I see one way here and another on StackOverflow. Also, for my personal curiosity, which name is your personal name and which is a family name (or patronymic?)?
2. How would you feel about similarly documenting the (presumably somewhat simpler) invariants in `aptyMiddle`, while you have these ideas running around in your head? I've struggled for years to try to hold all the ideas there together at any one time.

2020-04-13 18:33 UTC, Lysxia commented
Great!

1. Li-yao is my first name, so you can credit me as Li-yao Xia. (Chinese people commonly call each other by family-name-given-name so I'm used to both ways.)

2. Sure!

2020-04-13 18:37 UTC, closed without merging

2020-04-13 18:37 UTC, treeowl commented
Thanks a lot!